### ISSUE TITLE
Distribution

### ISSUE THREAD

**Issue by BruceZhang1993** [BruceZhang1993/FastOCR#2]
**Linux**

- [x] Arch Linux derivative  [AUR](https://aur.archlinux.org/packages/fastocr/)  ~~Thanks to myself~~
- [x] NixOS/Nix [fastocr](https://github.com/berberman/flakes/blob/master/packages/fastocr/default.nix)  Thanks to [Potato Hatsue](https://github.com/berberman)
- [ ] Debian/Ubuntu derivative
- [ ] Gentoo derivative
- [x] AppImage

...

**Windows**

- [x] PyInstaller (Exe)
- [x] PyInstaller (Zip)

**macOS**

- [x] PyInstaller (App)

**Common**

- [x] PyPI   [FastOCR](https://pypi.org/project/fastocr/)

**Comment by a15355447898a** [comment]
请问有考虑过使用AppImage来打包吗?

**Comment by BruceZhang1993** [comment]
> 请问有考虑过使用AppImage来打包吗?

好的 研究下
