### ISSUE TITLE
[功能请求]可否能支持使用快捷键使用软件

### ISSUE THREAD

**Issue by a15355447898a** [BruceZhang1993/FastOCR#8]
现在的使用要鼠标移动到桌面托盘点击软件图标才能使用
移动的位置太大
如果能支持使用自定义快捷键开启软件的功能就好了

**Comment by BruceZhang1993** [comment]
对于 Linux 桌面，因为内置了 DBus 支持可以通过自定义快捷键完成绑定，对于 KDE 进入系统设置 - 快捷键 - 自定义快捷键 - 导入以下文件即可

https://gist.github.com/BruceZhang1993/1c325cc9932cbe807d8f7010c684f0b7

其他桌面环境可把快捷键绑定到下面的命令

`dbus-send --type="method_call" --dest=io.github.brucezhang1993.FastOCR /io/github/brucezhang1993/FastOCR io.github.brucezhang1993.FastOCR.captureToClipboard int32:0 boolean:false`

Windows 和 macOS 暂时不支持
