### ISSUE TITLE
[Feature Request] Please support Mathpix API

### ISSUE THREAD

**Issue by sukanka** [BruceZhang1993/FastOCR#9]
**Describe the feature**
Could you please add support for mathpix API so that users can use this to copy and paste math formulars?
Reference: https://mathpix.com/ocr

**Comment by BruceZhang1993** [comment]
mathpix api is requesting an accessible url of image, so we need to support an image pastebin first. Using a public pastebin is kind of risky.
bad news. TT

**Comment by WhiredPlanck** [comment]
> mathpix api is requesting an accessible url of image, so we need to support an image pastebin first. Using a public pastebin is kind of risky. bad news. TT

According to [their API references](https://docs.mathpix.com/#process-an-image):
"_... For backward compatibility a client also may post a JSON body containing the base64 encoding of the image in the src field._" 

We can get the base64 coding of the image passed to the API.

**Comment by BruceZhang1993** [comment]
Implemented in https://github.com/BruceZhang1993/FastOCR/commit/ee4f3a92d61db95f35a1c0e2fcb56068e6ec13a6, but no account to test.
